// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Test} from "forge-std/Test.sol";
import {EscrowContract} from "../src/EscrowContract.sol";
import {EscrowContractFactory} from "../src/EscrowContractFactory.sol";

/**
 * Generates the test vector every off-chain address predictor is pinned to.
 *
 * chainservice, the browser and (soon) the AP2 adapter each derive escrow addresses without
 * asking the chain — that is the whole point of a counterfactual address. They are therefore
 * replicas of what THIS factory does, and the factory is the only authority: an implementation
 * that disagrees with it sends funds to somewhere nothing can be deployed, where they are
 * unreachable rather than merely misplaced.
 *
 * Writing the cases out rather than asserting them here is deliberate. Three implementations
 * that each agree with the Solidity is a stronger guarantee than one shared implementation
 * agreeing with itself — but only if a change to the salt cannot quietly leave all three
 * pinned to a stale answer. Hence the committed file and the CI check that regenerates it:
 * changing the salt now forces the vector to change, and that is the prompt to go and update
 * the consumers.
 *
 * Regenerate with:  forge test --match-contract PredictVectorTest
 */
contract PredictVectorTest is Test {
    EscrowContract internal implementation;
    EscrowContractFactory internal factory;

    address constant TOKEN = 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913;
    address constant BUYER = 0x70997970C51812dc3A010C7d01b50e0d17dc79C8;
    address constant SELLER = 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC;
    address constant ARBITER = 0x9bB8e809EA6F5A74f46027D8016641D9cE9A149C;
    address constant OTHER_ARBITER = 0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc;
    address constant PARTNER = 0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65;

    function setUp() public {
        implementation = new EscrowContract(address(0xDEFA17), bytes20(0));
        factory = new EscrowContractFactory(address(0x1), address(implementation), address(0), address(0), bytes20(0));
    }

    function testWriteVectors() public {
        string memory json = string.concat(
            "{\n",
            '  "_comment": "Generated by PredictVectorTest in the contracts repo. Do not edit by hand.",\n',
            '  "_regenerate": "forge test --match-contract PredictVectorTest",\n',
            '  "factory": "',
            vm.toString(address(factory)),
            '",\n',
            '  "implementation": "',
            vm.toString(address(implementation)),
            '",\n',
            '  "cases": [\n',
            _case(
                Vector(
                    "canonical",
                    TOKEN,
                    BUYER,
                    SELLER,
                    1000000000,
                    1793500000,
                    ARBITER,
                    "507f1f77bcf86cd799439011",
                    address(0),
                    0
                )
            ),
            ",\n",
            _case(
                Vector(
                    "instant-transfer-no-dispute-window",
                    TOKEN,
                    BUYER,
                    SELLER,
                    1000000000,
                    0,
                    ARBITER,
                    "507f1f77bcf86cd799439011",
                    address(0),
                    0
                )
            ),
            ",\n",
            _case(
                Vector(
                    "same-terms-different-external-id",
                    TOKEN,
                    BUYER,
                    SELLER,
                    1000000000,
                    1793500000,
                    ARBITER,
                    "507f1f77bcf86cd799439012",
                    address(0),
                    0
                )
            ),
            ",\n",
            _case(
                Vector(
                    "same-terms-different-arbiter",
                    TOKEN,
                    BUYER,
                    SELLER,
                    1000000000,
                    1793500000,
                    OTHER_ARBITER,
                    "507f1f77bcf86cd799439011",
                    address(0),
                    0
                )
            ),
            ",\n",
            _case(
                Vector(
                    "large-amount",
                    TOKEN,
                    BUYER,
                    SELLER,
                    123456789012345,
                    1793500000,
                    ARBITER,
                    "abcdef012345678901234567",
                    address(0),
                    0
                )
            ),
            ",\n",
            // Split cases. These take the second salt branch (partner and partnerBps appended),
            // and carry the EIP-712 digest FEE_SPLIT_SIGNER signs, so signing code is pinned too.
            // The digest binds chainid and factory: it is valid for THIS vector's factory at
            // chainid 31337 only, which is exactly what makes it a check of the encoding.
            _case(
                Vector(
                    "partner-split-half-fee",
                    TOKEN,
                    BUYER,
                    SELLER,
                    1000000000,
                    1793500000,
                    ARBITER,
                    "507f1f77bcf86cd799439011",
                    PARTNER,
                    5000
                )
            ),
            ",\n",
            _case(
                Vector(
                    "partner-split-whole-fee",
                    TOKEN,
                    BUYER,
                    SELLER,
                    1000000000,
                    1793500000,
                    ARBITER,
                    "507f1f77bcf86cd799439011",
                    PARTNER,
                    10000
                )
            ),
            "\n  ]\n}\n"
        );

        vm.writeFile("counterfactual-vectors.json", json);
    }

    /// Bundled because eight loose parameters plus the concat overflows the stack (via_ir off).
    struct Vector {
        string name;
        address token;
        address buyer;
        address seller;
        uint256 amount;
        uint256 expiryTimestamp;
        address arbiter;
        string contractserviceId;
        address partner;
        uint16 partnerBps;
    }

    function _case(Vector memory v) internal view returns (string memory) {
        bytes32 externalId = keccak256(bytes(v.contractserviceId));
        if (v.partnerBps == 0) {
            address expected = factory.getContractAddress(
                v.token, v.buyer, v.seller, v.amount, v.expiryTimestamp, v.arbiter, externalId
            );
            return string.concat(
                _terms(v),
                '      "externalId": "',
                vm.toString(externalId),
                '",\n',
                '      "expectedAddress": "',
                vm.toString(expected),
                '"\n    }'
            );
        }
        return string.concat(_terms(v), '      "externalId": "', vm.toString(externalId), '",\n', _split(v, externalId));
    }

    function _split(Vector memory v, bytes32 externalId) internal view returns (string memory) {
        EscrowContractFactory.FeeSplit memory split = EscrowContractFactory.FeeSplit(v.partner, v.partnerBps);
        address expected = factory.getContractAddressWithSplit(
            v.token, v.buyer, v.seller, v.amount, v.expiryTimestamp, v.arbiter, externalId, split
        );
        bytes32 digest = factory.feeSplitDigest(
            v.token, v.buyer, v.seller, v.amount, v.expiryTimestamp, v.arbiter, externalId, split
        );
        return string.concat(
            '      "partner": "',
            vm.toString(v.partner),
            '",\n',
            '      "partnerBps": ',
            vm.toString(uint256(v.partnerBps)),
            ",\n",
            '      "chainId": ',
            vm.toString(block.chainid),
            ",\n",
            '      "feeSplitDigest": "',
            vm.toString(digest),
            '",\n',
            '      "expectedAddress": "',
            vm.toString(expected),
            '"\n    }'
        );
    }

    function _terms(Vector memory v) internal pure returns (string memory) {
        return string.concat(
            "    {\n",
            '      "name": "',
            v.name,
            '",\n',
            '      "tokenAddress": "',
            vm.toString(v.token),
            '",\n',
            '      "buyer": "',
            vm.toString(v.buyer),
            '",\n',
            '      "seller": "',
            vm.toString(v.seller),
            '",\n',
            '      "amount": "',
            vm.toString(v.amount),
            '",\n',
            '      "expiryTimestamp": ',
            vm.toString(v.expiryTimestamp),
            ",\n",
            '      "arbiter": "',
            vm.toString(v.arbiter),
            '",\n',
            '      "contractserviceId": "',
            v.contractserviceId,
            '",\n'
        );
    }
}
